module.exports = {
  STRUGGLE_ATTEMPTS: 3,
  STRUGGLE_TIME: 1800,
  PACING_SLOW_FACTOR: 1.8,
  PACING_FAST_FACTOR: 0.3,
  LESSON_DIFFICULTY_THRESHOLD: 2,
  COURSE_DROPOFF_MIN_LESSONS: 2,
  COURSE_DROPOFF_RATE: 0.5,
};
